name: flutter_native_strings
description: A command-line tool that simplifies the task of adding native Android and iOS string resources to your Flutter app.
version: 0.0.1
repository: https://github.com/victoreronmosele/flutter-native-strings

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^6.0.1
  file: ^6.1.2

dev_dependencies:
  mockito: ^5.1.0
  test: ^1.20.2
